"""Ports -- the interfaces the application layer depends on.

Concrete implementations live in :mod:`clippycap.infra` (SQLite repositories, ffmpeg adapters, the
filesystem scanner) and :mod:`clippycap.plugins_runtime` (registries, the event bus, the job
queue). The application layer never imports a concrete implementation; it is handed one through
the composition root.
"""

from __future__ import annotations

from collections.abc import Callable, Iterable, Mapping, Sequence
from contextlib import AbstractContextManager
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal, Protocol

from .entities import (
    Asset,
    AssetPath,
    Note,
    Reference,
    ReferenceType,
    SavedView,
    Source,
    Tag,
)
from .query import AssetFilter

# --------------------------------------------------------------------------- repositories


class AssetRepository(Protocol):
    def add(self, asset: Asset) -> Asset: ...
    def get(self, asset_id: int) -> Asset | None: ...
    def get_by_hash(self, identity_hash: str) -> Asset | None: ...
    def update(self, asset: Asset) -> None: ...
    def delete(self, asset_id: int) -> None: ...
    def search(
        self, *, filter: AssetFilter, sort_key: str, offset: int, limit: int
    ) -> tuple[list[Asset], int]: ...
    def touch_seen(self, asset_id: int) -> None: ...
    def touch_opened(self, asset_id: int) -> None: ...
    def set_missing(self, asset_id: int, missing: bool) -> None: ...
    # paths
    def add_path(self, path: AssetPath) -> AssetPath: ...
    def get_paths(self, asset_id: int) -> list[AssetPath]: ...
    def find_by_path(self, path: str) -> Asset | None: ...
    def upsert_path(self, asset_id: int, path: str, volume_id: str | None) -> None: ...
    def rename_path(self, old_path: str, new_path: str) -> None: ...
    def reconcile_paths_under(self, root: str, seen_paths: Iterable[str]) -> list[int]: ...
    def all_paths_absent(self, asset_id: int) -> bool: ...


class TagRepository(Protocol):
    def add(self, tag: Tag) -> Tag: ...
    def get(self, tag_id: int) -> Tag | None: ...
    def get_by_name(self, name: str) -> Tag | None: ...
    def list_all(self) -> list[Tag]: ...
    def update(self, tag: Tag) -> None: ...
    def delete(self, tag_id: int) -> None: ...
    def reorder(self, ordered_ids: Sequence[int]) -> None: ...
    def asset_count(self, tag_id: int) -> int: ...
    # asset <-> tag links
    def apply(self, asset_id: int, tag_id: int) -> bool: ...
    def unapply(self, asset_id: int, tag_id: int) -> bool: ...
    def tag_ids_for_asset(self, asset_id: int) -> list[int]: ...
    def tag_ids_for_assets(self, asset_ids: Sequence[int]) -> dict[int, list[int]]: ...


class NoteRepository(Protocol):
    def add(self, note: Note) -> Note: ...
    def get(self, note_id: int) -> Note | None: ...
    def update(self, note: Note) -> None: ...                                # body + updated_at only
    def retime(self, note_id: int, timestamp_ms: int | None, end_timestamp_ms: int | None) -> None: ...
    def delete(self, note_id: int) -> None: ...
    def list_for_asset(self, asset_id: int) -> list[Note]: ...
    def general_note(self, asset_id: int) -> Note | None: ...
    def count_for_asset(self, asset_id: int) -> int: ...
    def counts_for_assets(self, asset_ids: Sequence[int]) -> dict[int, int]: ...
    # note tags
    def set_tags(self, note_id: int, tag_ids: Sequence[int]) -> None: ...
    def tag_ids_for_note(self, note_id: int) -> list[int]: ...


class ReferenceTypeRepository(Protocol):
    def add(self, rt: ReferenceType) -> ReferenceType: ...
    def get(self, type_id: int) -> ReferenceType | None: ...
    def get_by_name(self, name: str) -> ReferenceType | None: ...
    def list_all(self) -> list[ReferenceType]: ...
    def update(self, rt: ReferenceType) -> None: ...
    def delete(self, type_id: int) -> None: ...
    def reorder(self, ordered_ids: Sequence[int]) -> None: ...


class ReferenceRepository(Protocol):
    def add(self, ref: Reference) -> Reference: ...
    def get(self, ref_id: int) -> Reference | None: ...
    def update(self, ref: Reference) -> None: ...
    def delete(self, ref_id: int) -> None: ...
    def list_outgoing(self, asset_id: int) -> list[Reference]: ...
    def list_incoming(self, asset_id: int) -> list[Reference]: ...
    def count_for_asset(self, asset_id: int) -> int: ...
    def counts_for_assets(self, asset_ids: Sequence[int]) -> dict[int, int]: ...


class SourceRepository(Protocol):
    def add(self, source: Source) -> Source: ...
    def get(self, source_id: int) -> Source | None: ...
    def get_by_path(self, path: str) -> Source | None: ...
    def list_all(self) -> list[Source]: ...
    def update(self, source: Source) -> None: ...
    def delete(self, source_id: int) -> None: ...
    def touch_scanned(self, source_id: int) -> None: ...


class SavedViewRepository(Protocol):
    def add(self, view: SavedView) -> SavedView: ...
    def get(self, view_id: int) -> SavedView | None: ...
    def list_all(self) -> list[SavedView]: ...
    def update(self, view: SavedView) -> None: ...
    def delete(self, view_id: int) -> None: ...
    def reorder(self, ordered_ids: Sequence[int]) -> None: ...


class HashCacheStore(Protocol):
    """Pure performance cache: ``(path, size, mtime) -> identity hash`` so re-scans skip unchanged files."""

    def get(self, path: str, size: int, mtime_ns: int) -> str | None: ...
    def put(self, path: str, size: int, mtime_ns: int, identity_hash: str) -> None: ...
    def forget(self, path: str) -> None: ...


class MetaStore(Protocol):
    """A small key/value store for bookkeeping (schema version, first-run flag, ...)."""

    def get(self, key: str) -> str | None: ...
    def set(self, key: str, value: str) -> None: ...


# --------------------------------------------------------------------------- unit of work / database


class UnitOfWork(Protocol):
    """All repositories sharing one transaction. Use as a context manager; commit explicitly."""

    assets: AssetRepository
    tags: TagRepository
    notes: NoteRepository
    reference_types: ReferenceTypeRepository
    references: ReferenceRepository
    sources: SourceRepository
    saved_views: SavedViewRepository
    hash_cache: HashCacheStore
    meta: MetaStore

    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class Database(Protocol):
    def initialise(self) -> None: ...                       # create/migrate the schema (idempotent)
    def transaction(self) -> AbstractContextManager[UnitOfWork]: ...


# --------------------------------------------------------------------------- identity & media


class IdentityStrategy(Protocol):
    """Computes the content identity of a file. Implementations are registered by ``name``."""

    name: str

    def compute(self, path: Path, size: int) -> str: ...    # algo-prefixed, e.g. "b3:<hex>"


class MetadataExtractor(Protocol):
    def extract(self, path: Path) -> dict[str, Any]: ...    # media-type-specific; may be {}


class Thumbnailer(Protocol):
    """Generates a thumbnail server-side. ``available is False`` => the frontend captures one."""

    available: bool

    def make(self, path: Path, out_path: Path, *, metadata: Mapping[str, Any]) -> bool: ...


class MediaTypeProvider(Protocol):
    """Everything the core needs to handle one kind of media. Registered by ``media_type``."""

    media_type: str
    extensions: frozenset[str]                              # lowercase, no leading dot
    identity_strategy_name: str
    player_kind: str                                        # frontend hint: "video" | "image" | "audio"

    def detect(self, path: Path) -> bool: ...
    def extract_metadata(self, path: Path) -> dict[str, Any]: ...
    def make_thumbnail(self, path: Path, out_path: Path, *, metadata: Mapping[str, Any]) -> bool: ...
    def display_title(self, path: Path, metadata: Mapping[str, Any]) -> str: ...


class VideoEditor(Protocol):
    """Cuts and re-assembles video files (ffmpeg-backed). Times are in **milliseconds**.

    ``available is False`` when no ffmpeg binary is configured -- callers must check it first.
    """

    available: bool

    def keep_range(self, source: Path, out_path: Path, *, start_ms: int, end_ms: int) -> bool:
        """Write ``out_path`` containing only ``source``'s ``[start_ms, end_ms]``."""
        ...

    def remove_range(self, source: Path, out_path: Path, *, start_ms: int, end_ms: int) -> bool:
        """Write ``out_path`` = ``source`` with ``[start_ms, end_ms]`` cut out (the surrounding parts)."""
        ...

    def resolve_cut_start(self, source: Path, requested_ms: int) -> int:
        """The source time (ms) a cut starting at ``requested_ms`` will *actually* begin at (it snaps
        to a keyframe / frame boundary), so notes can be shifted by the right amount; returns
        ``requested_ms`` if it cannot be determined."""
        ...


# --------------------------------------------------------------------------- background jobs


JobState = Literal["pending", "running", "done", "error"]


@dataclass
class JobHandle:
    """Live status of a background job (a scan, a thumbnail batch, ...)."""

    id: str
    name: str
    state: JobState = "pending"
    scanned: int = 0
    total: int | None = None
    message: str = ""
    error: str | None = None


class ProgressReporter(Protocol):
    def update(self, scanned: int, total: int | None = None, message: str = "") -> None: ...


class JobQueue(Protocol):
    def submit(self, name: str, run: Callable[[ProgressReporter], None]) -> str: ...
    def get(self, job_id: str) -> JobHandle | None: ...
    def list_all(self) -> list[JobHandle]: ...


# --------------------------------------------------------------------------- portability


class PortableExporter(Protocol):
    format_id: str

    def export(self, uow: UnitOfWork, out_path: Path) -> None: ...


class PortableImporter(Protocol):
    format_id: str

    def import_into(self, uow: UnitOfWork, in_path: Path) -> Mapping[str, int]: ...   # summary counts
